export const GENRES = [
  { id: 1,  name: "Action" },
  { id: 2,  name: "Adventure" },
  { id: 5,  name: "Avant Garde" },
  { id: 46, name: "Award Winning" },
  { id: 28, name: "Boys Love" },
  { id: 4,  name: "Comedy" },
  { id: 8,  name: "Drama" },
  { id: 10, name: "Fantasy" },
  { id: 26, name: "Girls Love" },
  { id: 47, name: "Gourmet" },
  { id: 14, name: "Horror" },
  { id: 7,  name: "Mystery" },
  { id: 22, name: "Romance" },
  { id: 24, name: "Sci-Fi" },
  { id: 36, name: "Slice of Life" },
  { id: 30, name: "Sports" },
  { id: 37, name: "Supernatural" },
  { id: 41, name: "Suspense" },
  { id: 9,  name: "Ecchi" },
  { id: 50, name: "Adult Cast" },
  { id: 51, name: "Anthropomorphic" },
  { id: 52, name: "CGDCT" },
  { id: 53, name: "Childcare" },
  { id: 54, name: "Combat Sports" },
  { id: 81, name: "Crossdressing" },
  { id: 55, name: "Delinquents" },
  { id: 39, name: "Detective" },
  { id: 56, name: "Educational" },
  { id: 57, name: "Gag Humor" },
  { id: 58, name: "Gore" },
  { id: 35, name: "Harem" },
  { id: 59, name: "High Stakes Game" },
  { id: 13, name: "Historical" },
  { id: 60, name: "Idols (Female)" },
  { id: 61, name: "Idols (Male)" },
  { id: 62, name: "Isekai" },
  { id: 63, name: "Iyashikei" },
  { id: 64, name: "Love Polygon" },
  { id: 65, name: "Magical Sex Shift" },
  { id: 66, name: "Mahou Shoujo" },
  { id: 17, name: "Martial Arts" },
  { id: 18, name: "Mecha" },
  { id: 67, name: "Medical" },
  { id: 38, name: "Military" },
  { id: 19, name: "Music" },
  { id: 6,  name: "Mythology" },
  { id: 68, name: "Organized Crime" },
  { id: 69, name: "Otaku Culture" },
  { id: 20, name: "Parody" },
  { id: 70, name: "Performing Arts" },
  { id: 71, name: "Pets" },
  { id: 40, name: "Psychological" },
  { id: 3,  name: "Racing" },
  { id: 72, name: "Reincarnation" },
  { id: 73, name: "Reverse Harem" },
  { id: 21, name: "Samurai" },
  { id: 23, name: "School" },
  { id: 75, name: "Showbiz" },
  { id: 29, name: "Space" },
  { id: 11, name: "Strategy Game" },
  { id: 31, name: "Super Power" },
  { id: 76, name: "Survival" },
  { id: 77, name: "Team Sports" },
  { id: 78, name: "Time Travel" },
  { id: 32, name: "Vampire" },
  { id: 79, name: "Video Game" },
  { id: 80, name: "Visual Arts" },
  { id: 48, name: "Workplace" },
  { id: 82, name: "Urban Fantasy" },
  { id: 83, name: "Villainess" },
  { id: 43, name: "Josei" },
  { id: 15, name: "Kids" },
  { id: 42, name: "Seinen" },
  { id: 25, name: "Shoujo" },
  { id: 27, name: "Shounen" },
];
